# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

  
steps:

  - task: DotNetCoreCLI@2
    inputs:
      command: build
      arguments: -p:Version=$(Build.BuildNumber)

  - task: Snyk@2
    inputs:
     multiFile: true
     files: |
       #yarn.lock
       #package.json
       #package-lock.json
       #Gemfile
       #Gemfile.lock
       #pom.xml
       #Pipfile
       #requirements.txt
       #build.gradle
       #build.gradle.kts
       #build.sbt
       #Gopkg.lock
       #**/vendor/vendor.json
       #**/obj/project.assets.json
       #packages.config
       #composer.lock
       #**/app.config
       
       #!**/node_modules/**/*
     protect: false
     test: true
     monitor: false
     authType: 'token'
     token: '$(Snyk.Token)'
     failBuild: false
     dev: false
     trustPolicies: false