name: $(Date:yyyy.MM.dd).$(Rev:r)
variables:
  SNYK_TOKEN: 
jobs:
- job:
  steps:
  - task: Npm@1
    displayName: 'Install Snyk.io'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install -g snyk'

  - script: |
      snyk auth $(SNYK_TOKEN)
      snyk test
    displayName: 'Scan dependencies for vulnerabilities with Snyk'

  - script: |
      snyk monitor
    displayName: 'Setup dependency vulnerability monitoring with Snyk'


  - task: DotNetCoreCLI@2
    inputs:
      command: build
      arguments: -p:Version=$(Build.BuildNumber)