name: $(Date:yyyy.MM.dd).$(Rev:r)
variables:
  SNYK_TOKEN: 3e74cf14-a819-4424-9652-aee1fb06348b
jobs:
- job:
  steps:
  - task: Npm@1
    displayName: 'Install Npm'
    inputs:
      command: 'install'
      verbose: false

  - script: |
      npm install -g snyk
    displayName: 'Install Snyk.io'
    
  - script: |
      snyk auth $(SNYK_TOKEN)
      snyk test
    displayName: 'Scan dependencies for vulnerabilities with Snyk'

  - script: |
      snyk monitor
    displayName: 'Setup dependency vulnerability monitoring with Snyk'


  - task: DotNetCoreCLI@2
    inputs:
      command: build
      arguments: -p:Version=$(Build.BuildNumber)